AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Website Content Extractor Lambda Function

Resources:
  ContentExtractorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      MemorySize: 512
      Timeout: 30
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: get
      Environment:
        Variables:
          PYTHONPATH: /var/task

Outputs:
  ContentExtractorFunction:
    Description: "Content Extractor Lambda Function ARN"
    Value: !GetAtt ContentExtractorFunction.Arn
  ContentExtractorApi:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"